config/routes.rb
WhichShiftButton::Application.routes.draw do
  root :to => 'press_shift#index'
  match '/press' => 'press_shift#press', :as => :press
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/press_shift_controller.rb
class PressShiftController < ApplicationController
  def index
    @cookie = cookies[:pressed]
  end
  
  def press
    if cookies[:pressed].present?
      # DO NOTHING!!!
    elsif params[:button] == 'left'
      REDIS.incr('left_count')
    elsif params[:button] == 'both'
      REDIS.incr('both_count')
    elsif params[:button] == 'right'
      REDIS.incr('right_count')
    end
    cookies.permanent[:pressed] = params[:button]
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/press_shift_helper.rb
module PressShiftHelper
end

app/views/layouts/application.html.haml
!!! Strict
%html{:lang =>"en"}
  %head
    %title Which shift button do you use? | For Science
    %meta{:name => 'description', :content => 'An experiment for science about which shift button people use.'}
    = stylesheet_link_tag 'application'
    
    - if Rails.env.production?
      :plain
        <script type="text/javascript">
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-495329-23']);
          _gaq.push(['_trackPageview']);
          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
        </script>
  %body
    #container
      = yield
    

app/views/press_shift/index.html.haml
- if @cookie
  :plain
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
      <script type="text/javascript">
        google.load("visualization", "1", {packages:["corechart"]});
        google.setOnLoadCallback(drawChart);
        function drawChart() {
          var data = new google.visualization.DataTable();
          data.addColumn('string', 'Task');
          data.addColumn('number', 'Hours per Day');
          data.addRows(3);
          data.setValue(0, 0, 'Left Shift');
          data.setValue(0, 1, #{REDIS.get('left_count') || '2'});
          
          data.setValue(1, 0, 'Both');
          data.setValue(1, 1, #{REDIS.get('both_count') || '2'});
          
          data.setValue(2, 0, 'Right Shift');
          data.setValue(2, 1, #{REDIS.get('right_count') || '1'});
          
          var chart = new google.visualization.PieChart(document.getElementById('science_chart'));
          chart.draw(data, {width: 500, height: 425, backgroundColor: '#eeeeee', fontSize: 16, is3D: true, legend: 'bottom'});
        }
      </script>

  %h1
    Thanks for contributing to science!
  
  :plain
    <a href="http://twitter.com/share" class="twitter-share-button left" data-count="horizontal" data-text="For Science: Which shift button do you use?">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
  :plain
    <div id="fb-root" class="left"></div><script src="http://connect.facebook.net/en_US/all.js#appId=175519085838808&amp;xfbml=1"></script><fb:like href="" send="true" width="350" show_faces="true" font=""></fb:like>
  
  #science_chart
  
  %p#lols
    %a#just_science{:href => 'http://justforscience.com/'} want MORE science?
    Mashin' down the left shift
    %br
    Holdin' down the right shift
    %br
    Gotta make my mind up
    %br
    Which shift can I take?
  
  %br
  
  :plain
    <script type="text/javascript"><!--
    google_ad_client = "ca-pub-6859335418235928";
    /* Which Shift Button */
    google_ad_slot = "2384266649";
    google_ad_width = 468;
    google_ad_height = 60;
    //-->
    </script>
    <script type="text/javascript"
    src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
    </script>
  
  %br
- else
  #lol_topspace
    %h1
      Which shift button do you use?
    
    = link_to "Left Shift", press_path(:button => "left"), :method => :post, :id => 'shift_left', :rel => 'nofollow'
    = link_to "I use both", press_path(:button => "both"), :method => :post, :id => 'shift_both', :rel => 'nofollow'
    = link_to "Right Shift", press_path(:button => "right"), :method => :post, :id => 'shift_right', :rel => 'nofollow'